# review-epubmaker向けの設定ファイルの例。
# yamlファイルをReVIEWファイルのある場所に置き、
# 「review-epubmaker yamlファイル」を実行すると、<bookname>.epubファイルが
# 生成されます。
# このファイルはUTF-8エンコーディングで記述してください。

# ブック名(ファイル名になるもの。ASCII範囲の文字を使用)
bookname: free-as-in-freedom
# 書名
booktitle: 自由としてのフリー(2.0) リチャード・ストールマンと自由ソフトウェア革命
# 著者
aut: サム・ウィリアムズ/リチャード・ストールマン
trl: 後藤洋/弓削光好
clb: 河内崇
prt_url: http://haleakala-avenue.style.coocan.jp/lealea/?%E8%87%AA%E7%94%B1%E3%81%A8%E3%81%97%E3%81%A6%E3%81%AE%E3%83%95%E3%83%AA%E3%83%BC%282.0%29%E3%83%AA%E3%83%81%E3%83%A3%E3%83%BC%E3%83%89%E3%83%BB%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB%E3%83%9E%E3%83%B3%E3%81%A8%E8%87%AA%E7%94%B1%E3%82%BD%E3%83%95%E3%83%88%E3%82%A6%E3%82%A7%E3%82%A2%E9%9D%A9%E5%91%BD
date: 2013-09-30
# description: 
# 以下はオプション
# prt: 出版社
# asn: Associated name
# ant: Bibliographic antecedent
# clb: 貢献者
# edt: 編集者
# dsr: デザイナ
# ill: イラストレータ
# pht: 撮影者
# trl: 翻訳者
# date: 刊行日
# rights: 権利表記
# description: ブックの説明
#
# coverfile: カバーページのbody要素内に挿入する内容を記述したファイル名
#coverfile: _cover.html
# coverimage: 表紙用画像ファイル
#coverimage: cover.jpg
# 固有IDに使用するドメイン
#urnid: http://www.aozora.gr.jp/cards/000081/card46322.html
# CSSファイル (yamlファイルおよびReVIEWファイルを置いたディレクトリにあること
#stylesheet: base.css
# 目次として抽出するレベル
toclevel: 2
# セクション番号を表示するレベル
secnolevel: 0
# review-compileに渡すパラメータ
params: --stylesheet=base.css
# 目次生成用？
mytoc: true
# 奥付生成用
colophon: true
texstyle: samplemacro
# pubhistory: |
#   底本：「銀河鉄道の夜」岩波文庫、岩波書店
#   　　　1951（昭和26）年10月25日初版発行
#   　　　1962（昭和37）年3月30日第13刷発行
#   底本の親本：「宮澤賢治全集　第三卷」十字屋書店
#   入力：高柳典子
#   校正：土屋隆
#   2006年9月17日作成
#   2010年11月1日修正
#   青空文庫作成ファイル：
#   このファイルは、インターネットの図書館、青空文庫（http://www.aozora.gr.jp/）で作られました。入力、校正、制作にあたったのは、ボランティアの皆さんです。
debug: true
